### ISSUE TITLE
Make unit: and index: standard across docs and examples

### ISSUE THREAD

**Issue by maggie44** [balena-labs-research/balena-virt#6]
The examples read (https://github.com/balena-labs-research/balenaVirt/blob/master/examples/guests.aarch64.yml):
```
      - if: virtio
        format: qcow2
        unit: 0
        file: /data/{{templateName}}{{guestId}}.qcow2
```

The docs read:
```
drive:
  - if: virtio
    format: qcow2
    file: /data/guest{{guestId}}.qcow2
    index: 0
    media: disk
```

Caused a bit of a pause while working out whether index: or unit: were necessary. We could standardise the docs and examples to use the same.
